# building the Client
language: cpp
os:
- linux
matrix:
  include:
    # GCC 5
    - env: Ubuntu Build
      dist: xenial
    - env: Ubuntu Build
      sudo: required
      dist: xenial
      compiler: clang
    - env: XERCES_CONFIGURE_ENCODER="--enable-transcoder-icu" ADDIONAL_LD=" -licuuc"
      dist: xenial
      compiler: clang
    - env: Ubuntu Build
      dist: bionic
      compiler: gcc
    # Xcode 9.4 g++
    - env: OSX_VERSION=10.10
      osx_image: xcode8.3
      os: osx
      # Xcode 9.4 Clang
    - env: OSX_VERSION=10.14
      osx_image: xcode10.1
      os: osx
    - env: OSX_VERSION=10.14
      osx_image: xcode11.3
      os: osx
    # Windows 2016 Server
    - env: CXX_FLAG="-MD"
      os: windows
      install:
        - cmake -G "Visual Studio 15 2017 Win64" -DBUILD_SHARED_LIBS:BOOL=OFF -DCMAKE_INSTALL_PREFIX:PATH=libs -DCMAKE_CONFIGURATION_TYPES="Release" -Dxmlch-type=wchar_t -DCMAKE_CXX_FLAGS_RELEASE:STRING="$CXX_FLAG -O2 -Ob2 -DNDEBUG" ..
      script:
        - cd ..
        - CMD //C runMSBuild_lib.bat "Release"
        - CMD //C runMSUnitTest.bat
    - env: CXX_FLAG="-MT"
      os: windows
      install:
        - cmake -G "Visual Studio 15 2017 Win64" -DBUILD_SHARED_LIBS:BOOL=OFF -DCMAKE_INSTALL_PREFIX:PATH=libs -DCMAKE_CONFIGURATION_TYPES="Release" -Dxmlch-type=wchar_t -DCMAKE_CXX_FLAGS_RELEASE:STRING="$CXX_FLAG -O2 -Ob2 -DNDEBUG" ..
      script:
        - cd ..
        - CMD //C runMSBuild_lib.bat "Release"
        - CMD //C runMSUnitTest.bat

before_install:
- cd ..
- git clone --branch v3.2.2 https://github.com/apache/xerces-c.git
- cd xerces-c
- mkdir build
- cd build

install:
- cmake .. -DBUILD_SHARED_LIBS=OFF -Dxmlch-type=uint16_t -Dnetwork=OFF

before_script:
- cmake --build . --config Release --target install
- cd ..
- cd ..
- cd libMVRgdtf
- mkdir build
- cd build
- cmake -DWIN_RUNTIME_LIB:STRING=$CXX_FLAG -DUNITTEST=true ..

script:
- make -j 2
- ./MvrGdtfUnitTest
