# building the Client
language: cpp
os:
- linux
matrix:
  include:
    # GCC 5
    - env: Ubuntu Build
      sudo: required
      dist: xenial
    - env: Ubuntu Build
      sudo: required
      dist: xenial
      compiler: clang
    - env: XERCES_CONFIGURE_ENCODER="--enable-transcoder-icu" ADDIONAL_LD=" -licuuc"
      sudo: required
      dist: xenial
      compiler: clang
    - env: Ubuntu Build
      sudo: required
      dist: bionic
      compiler: gcc
    # Xcode 9.4 g++
    - env: OSX_VERSION=10.10
      osx_image: xcode8.3
      os: osx
      # Xcode 9.4 Clang
    - env: OSX_VERSION=10.14
      osx_image: xcode10.1
      os: osx
    # Windows 2016 Server
    - env: runtimeLibFlag="/MT /O2 /Ob2 /DNDEBUG"
      os: windows
      script:
        - powershell -nologo -noprofile -command "& { Expand-Archive -Path shared\xerces-c-3.2.2.zip -DestinationPath shared\ -Force; }"
        - cd shared
        - cd xerces-c-3.2.2
        - mkdir build
        - cd build
        - cmake -G "Visual Studio 15 2017 Win64" -DBUILD_SHARED_LIBS:BOOL=OFF -DCMAKE_INSTALL_PREFIX:PATH=.\libs -DCMAKE_CONFIGURATION_TYPES:STRING=Release -DCMAKE_CXX_FLAGS_RELEASE:STRING=$runtimeLibFlag ..
        - cmake --build . --config Release --target install
        - cd ..\..\..\
        - copy "shared\xerces-c-3.2.2\build\libs\lib\xerces-c_3.lib" libs\xerces-c_3.lib /Y
        - CMD //C "runMSBuild.bat"

script:
- make dependencies -j 2
- make -j 2
- make test