# building the Client
language: cpp
os:
- linux
matrix:
  include:
    # GCC 5
    - env: Ubuntu Build
      sudo: required
      dist: xenial
    - env: Ubuntu Build
      sudo: required
      dist: xenial
      compiler: clang
    - env: XERCES_CONFIGURE_ENCODER="--enable-transcoder-icu" ADDIONAL_LD=" -licuuc"
      sudo: required
      dist: xenial
      compiler: clang
    - env: Ubuntu Build
      sudo: required
      dist: bionic
      compiler: gcc
    # Xcode 9.4 g++
    - env: OSX_VERSION=10.10
      osx_image: xcode8.3
      os: osx
      # Xcode 9.4 Clang
    - env: OSX_VERSION=10.14
      osx_image: xcode10.1
      os: osx
    - env: OSX_VERSION=10.14
      osx_image: xcode11.3
      os: osx
    # Windows 2016 Server
    - env: CXX_FLAG="-MD"
      os: windows
      script:
        - CMD //C runMSBuild_lib.bat "Release"
    - env: CXX_FLAG="-MT"
      os: windows
      script:
        - CMD //C runMSBuild_lib.bat "Release"

install:
- mkdir build
- cd build
- cmake -DWIN_RUNTIME_LIB:STRING=$CXX_FLAG -DUNITTEST=true ..
- cd ..

script:
- cd build
- make -j 2
- ./MvrGdtfUnitTest