# building the Client
language: cpp
os:
- linux
matrix:
  include:
    # GCC 5
    - env: Ubuntu Build
      sudo: required
      dist: xenial
    - env: Ubuntu Build
      sudo: required
      dist: xenial
      compiler: clang
    # Xcode 9.4 g++
    - env: OSX_VERSION=10.10
      osx_image: xcode8.3
      os: osx
      # Xcode 9.4 Clang
    - env: OSX_VERSION=10.14
      osx_image: xcode10.1
      os: osx
    # Windows 2016 Server
    - env: Windows 2016 Server
      os: windows
      script:
        - CMD //C "runMSBuild.bat"

script:
- make
- make test