# building the Client
language: cpp
os:
- linux
matrix:
  include:
    # GCC 5
    - env: Ubunt uBuild
      sudo: required
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
    # Xcode 9.4 Clang
    - env: OSX build
      osx_image: xcode9.4
      os: osx
	# Windows
    - env: Win build
      os: windows


script:
- make