name: Build Static

on:
    workflow_dispatch:

jobs:
    build:

        runs-on: windows-latest

        strategy:
            matrix:
                visual-studio-version: [2022]
                arch: [x64]

        steps:
        # Xerces-C - setup and build
        - name: Xerces-C - prepare
          run: |
            mkdir xerces-c
            cd xerces-c
            curl -o xerces-c.zip https://dlcdn.apache.org//xerces/c/3/sources/xerces-c-3.2.5.zip
            tar -xf xerces-c.zip --strip-components=1

        - name: Xerces-C - configure
          run: |
            mkdir build
            cd build
            cmake .. ^
            -G "Visual Studio 17 2022" -A x64 ^
            -DCMAKE_INSTALL_PREFIX:PATH=libs ^
            -DCMAKE_CXX_FLAGS="-MD /DWIN32 /D_WINDOWS -O2 -Ob2 -DNDEBUG" ^
            -DCMAKE_C_FLAGS="/DWIN32 /D_WINDOWS /W3" ^
            -DBUILD_SHARED_LIBS:BOOL=FALSE ^
            -Dxmlch-type=wchar_t

        - name: Xerces-C - build
          run: msbuild ALL_BUILD.vcxproj /p:Configuration=MinSizeRel

        - name: Xerces-C - install
          run: msbuild INSTALL.vcxproj /p:Configuration=MinSizeRel

        - name: Xerces-C - end
          run: cd ../..

        # Boost - setup and build
        - name: Boost - prepare
          run: |
            mkdir boost
            cd boost
            curl -o boost.zip https://archives.boost.io/release/1.86.0/source/boost_1_86_0.zip
            tar -xf boost.zip --strip-components=1
            cd ..

        # libMVRGdtf - setup and build
        - name: libMVRGdtf - prepare
          run: |
            mkdir libMVRgdtf
            cd libMVRgdtf

        - name: libMVRGdtf - checkout repository
          uses: actions/checkout@v4
          with:
            path: libMvrGdtf
 
        - name: libMVRGdtf - configure
          run: |
            cd libMVRgdtf
            mkdir build
            cd build
            cmake .. ^
            -DCMAKE_INSTALL_PREFIX:PATH=libs ^
            -DWIN_RUNTIME_LIB=-MD ^
            -DXERCES_INCLUDE_PATH="..\xerces-c\build\libs\include;..\xerces\src" ^
            -DXERCES_LIB_PATH="..\xerces\build\libs\lib" ^
            -DXERCES_ROOT_PATH="..\xerces-c"
            
            msbuild INSTALL.vcxproj /p:Configuration=MinSizeRel

        - name: libMVRGdtf - compile
          run: msbuild ALL_BUILD.vcxproj /p:Configuration=MinSizeRel

        - name: libMVRGdtf - install
          run: msbuild INSTALL.vcxproj /p:Configuration=MinSizeRel

        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: libMVRgdtf
            path: |
                ../libs/MinSizeRel/MvrGdtf-MD.lib

