name: Release on NPM

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository under ./libMvrGdtf
        uses: actions/checkout@v4
        with:
          path: libMvrGdtf
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.ADMIN_TOKEN }}
      
      - name: Test pushable
        run: git push --dry-run 

      - name: Build
        uses: ./libMvrGdtf/.github/actions/build-lib

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PKG_KEY }}
        working-directory: libMvrGdtf 
        run: |
          npm install
          npm run release
